### ISSUE TITLE
Incorrect parameter: microsoft-build-tools

### ISSUE THREAD

**Issue by jbest84** [saltstack/salt-winrepo#813]
There is no /qn flag for the BuildTools_Full.exe installer. This causes the installer to open a winforms dialog with the list of params. The minion keeps the process open indefinitely.

**Comment by TheBigBear** [comment]
@jbest84 thanks for reporting this

**Comment by TheBigBear** [comment]
@jbest84 what is the 'quiet' or 'silent' switch for this installer? Do you know? Is there one listed in the open winforms dialog?

**Comment by jbest84** [comment]
/Quite (/Q) and /Silent (/S)

I took a screenshot of the full list:
![builttools_params](https://cloud.githubusercontent.com/assets/354553/14895369/1b31d3c2-0d2d-11e6-8c43-caf0205caa72.PNG)

**Comment by jbest84** [comment]
I am relatively new to salt. Is there a way these package flags can be overriden in my state files via an include/extend? I tried doing this with no luck:

```
include:
  - win.winrepo-ng.salt-winrepo-ng.microsoft-build-tools

extend:
  microsoft-build-tools:
    install_flags: '/Q /NoRestart'

dotnet:
  pkg.installed: 
    - pkgs:
      - microsoft-build-tools
```
